#!/bin/sh
. "$HOOKS_DIR/core/lib.sh"

cfg_bool hooks.ginshio.pre-commit.warn-protected-enabled || exit 0

if echo "$CURRENT_BRANCH" | grep -q -E "$PROTECTED_BRANCH"; then
  log_warn "Commit to protected branch ($CURRENT_BRANCH), think before you type."
  if ! prompt_confirm; then
    log_warn "Abort..."
    exit 1
  fi
fi
