#!/bin/sh
# Avoid canceling the reference transaction in the case that `branchless` fails
git branchless hook reference-transaction "$@" || (
    echo 'branchless: Failed to process reference transaction!'
    echo 'branchless: Some events (e.g. branch updates) may have been lost.'
    echo 'branchless: This is a bug. Please report it.'
)
